### ISSUE TITLE
Struggling With XPaths containing brackets or equal signs

### ISSUE THREAD

**Issue by Roebou1989** [basiliscos/lua-xpath#2]
Hi,

I am struggling with using XPaths that contain any brackets or equal signs in them.
For example, here is my XML packet.
![image](https://github.com/basiliscos/lua-xpath/assets/52892685/b19d18ff-15a2-4251-ba54-4e136d7efdc4)

Here is my XPath:
`//member[name='TransactionId']/value/string`

This XPath returns nothing with the xpath.selectNodes method.

The following XPath does return rows, two records:
`//member`

Please advise if anything is perhaps configured incorrectly or how to specify the XPath in another way perhaps?

Thanks,
Rohan

**Comment by basiliscos** [comment]
Hi,

sorry, but it seems the original library version did not support full-powered xpath expressions. Patches welcome :)

**Comment by Roebou1989** [comment]
Any idea which XPaths are valid and which ones are not valid at this stage? Will see if I can add the functionality required for items that are not working.

**Comment by Roebou1989** [comment]
Added additional functionality in [PR](https://github.com/basiliscos/lua-xpath/pull/)

I am not able to link the PR to this ticket.

**Comment by basiliscos** [comment]
Hi, thank you. Will look at it a bit later (probably today or at the weekends). If everything is OK I'll upload to luarocks.

Thank you anyway :)

**Comment by basiliscos** [comment]
@thepeanutgalleryandco 

could you please, add a few tests to prove, that the new  functionality actually works?

```
luarocks install lua-testmore
luarocks install luaexpat
./test.sh
```

the `prove` utility can be found when you install system `perl`

**Comment by Roebou1989** [comment]
@basiliscos  done and comments added on the PR.
